# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f1b7db0287a18e207fcab2d48319b2b471e8768355871a6fed26a5371d0eed0bee0a87a494c95c4b55d5591d0c232468fcb8db623f0b7b8679ad8377206737a0

test:
  secret_key_base: c2aeb2afe908a15e8a67f771cb69606e1b257d66943b66e8ff58aa45455f4a36512d9ffc7e6a36f08687cb6abb1f47aedc3b36145f8d7360be3c904dcb462d5d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
